spring.application.name=auth
spring.security.user.name=user
spring.security.user.password=password
spring.datasource.url=jdbc:postgresql://localhost:5000/db?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.password=password
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=admin_user
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
